inherit_from:
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/master/.rubocop.yml
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/master/.rubocop-rspec.yml
  - https://raw.githubusercontent.com/wbotelhos/dotfiles/master/.rubocop-rspec_rails.yml
