require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Rails:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Lint/Debugger:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/ExampleLength:
  Max: 18

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%r': ()
    '%w': '[]'
    '%W': '[]'

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false
